#!/bin/bash
# removes all screenshot files in a directory
# note: only works for filenames starting with "Screen"

# variables

PROMPT="Type in the directory you wish to delete from \
(for example: /Users/username/Desktop). Otherwise \
type done to exit: "
BEAR_START=$'o____o \n( ･ω･) < Let\'s delete your screenshots! )\n(づ  )づ'
BEAR_DONE=$'o____o \n( ･ω･) < Goodbye! )\n(づ  )づ'
ORANGE="\e[38;5;208m"
SCREENSHOT="Screen"

# start 

printf "%s\n\n" "$BEAR_START"

while true; do
	read -p "$PROMPT" dir

	if [[ $dir == "done" ]]; then
		printf "%s\n\n" "Exiting..." "$BEAR_DONE"
		exit 0
	fi

	printf "%b" "$ORANGE[WARNING]: THIS WILL DELETE ALL SCREENSHOTS FROM THE $dir DIRECTORY."
	read -p $'Are you sure you want to continue? (y/n): \e[0m' reply

	path="$dir/$SCREENSHOT*.png"
	count=0
	if [[ $reply =~ ^[Yy]$ ]]; then
		for file in $path; do
			if [[ -f "$file" ]]; then 
				printf  "%s\n" "Removing $file..."
				rm "$file"
				((count++))
			else
				printf "%s\n\n" "No screenshots exist in $dir directory."
			fi
		done
		printf "%s\n\n" "$count screenshot(s) successfully removed from $dir."
	else 
		printf "%s\n\n" "Exiting..." "$BEAR_DONE"
		exit 0
	fi
done
